(()=>{
if(window.__dsWarmupCardioLoaded)return;window.__dsWarmupCardioLoaded=true;
const PROFILE_KEY='ds_profile_v2',AREA_ID='workoutArea',STYLE_ID='ds-warmup-cardio-style',PRE_ID='ds-workout-prep',POST_ID='ds-workout-post';
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{}}catch{return{}}}
function goal(){const g=String(profile().goal||profile().goalType||'gain').toLowerCase();return g==='lose'?'loss':g}
function round5(n){return Math.max(5,Math.round(n/5)*5)}
function workoutName(area){return area.querySelector('.workoutCard h2, h2')?.textContent.trim()||''}
function firstExerciseName(area){return area.querySelector('.exercise h3')?.textContent.trim()||'first exercise'}
function firstWorkingWeight(area){const ex=area.querySelector('.exercise');if(!ex)return 0;for(const n of ex.querySelectorAll('input[type="number"]')){const v=+n.value;if(Number.isFinite(v)&&v>0)return v}return 0}
function kind(name,area){const n=name.toLowerCase(),first=firstExerciseName(area);if(n.includes('lower')||/leg|squat|lunge|deadlift|calf/i.test(first))return'lower';if(n.includes('upper'))return'upper';return'full'}
function warmup(name,area){const k=kind(name,area),first=firstExerciseName(area),w=firstWorkingWeight(area);let cardio,moves;if(k==='lower'){cardio='5–8 min easy treadmill walk, incline walk, or bike. Finish warmer, not tired.';moves=['Leg swings × 8 each direction/side','Ankle rocks × 8–10/side','Bodyweight squats × 8–10','Reverse lunges × 5/side']}else if(k==='upper'){cardio='3–5 min easy treadmill, bike, or rower.';moves=['Arm circles × 10 each way','Band pull-aparts or cable face pulls × 12–15','Scapular push-ups × 8–10','Light shoulder external rotations × 8–10/side']}else{cardio='5 min easy treadmill, bike, or rower.';moves=['Arm circles × 10 each way','Leg swings × 8/side','Bodyweight squats × 8–10','Scapular push-ups × 8–10']}
let ramp=`Perform 2–4 lighter ramp-up sets for ${first} before your working sets.`;if(w>0){ramp=`${first}: about ${round5(w*.5)} lb × 8, ${round5(w*.7)} lb × 5, ${round5(w*.85)} lb × 2–3, then begin working sets. Adjust for machine starting resistance.`}return{cardio,moves,ramp}}
function cardioPlan(name){const g=goal(),n=name.toLowerCase(),upper=n.includes('upper'),full=n.includes('full body'),lower=n.includes('lower');if(g==='gain'||g==='strength')return upper||full?{show:true,title:'Easy conditioning',time:'15–20 min',text:'Zone 2 / conversational pace after lifting. Keep it easy enough that recovery and weight-gain training stay the priority.'}:{show:false};if(g==='recomp'||g==='maintain')return upper||full?{show:true,title:'Conditioning',time:'20–25 min',text:'Easy-to-moderate Zone 2 / conversational pace after lifting.'}:{show:false};if(g==='loss'){if(upper||full)return{show:true,title:'Fat-loss support',time:'20–30 min',text:'Zone 2 / brisk conversational pace after lifting.'};if(lower)return{show:true,title:'Separate cardio',time:'15–20 min',text:'Easy walk or bike later in the day or on a recovery day. Avoid turning the leg workout into conditioning.'}}return{show:false}}
function cooldown(name,area){const k=kind(name,area);if(k==='lower')return['Hip-flexor stretch · 30–45 sec/side','Hamstring stretch · 30–45 sec/side','Calf stretch · 30–45 sec/side'];if(k==='upper')return['Doorway chest stretch · 30–45 sec/side','Lat stretch · 30–45 sec/side','Cross-body shoulder stretch · 30–45 sec/side'];return['Hip-flexor stretch · 30 sec/side','Chest stretch · 30 sec/side','Lat stretch · 30 sec/side']}
function styles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent='.dsPrepCard{margin:12px 0;border:1px solid #3a3a3a;border-radius:16px;padding:14px;background:#101010}.dsPrepCard h3{margin:0 0 7px;font-size:16px}.dsPrepEyebrow{font-size:11px;font-weight:900;letter-spacing:.8px;color:#ff5960}.dsPrepMeta{margin:5px 0 10px;color:#ffbf47;font-weight:800;font-size:12px}.dsPrepList{margin:8px 0 0;padding-left:19px;color:#c7c7c7}.dsPrepList li{margin:5px 0}.dsPrepText{color:#b9b9b9;font-size:13px;line-height:1.45}.dsPrepBtn{margin-top:10px;border:1px solid #3b3b3b;background:#202020;color:#fff;border-radius:11px;padding:10px 12px;font-weight:800;min-height:42px}.dsPrepDivider{height:1px;background:#2f2f2f;margin:11px 0}';document.head.appendChild(s)}
function yogaButton(){const b=document.createElement('button');b.type='button';b.className='dsPrepBtn';b.textContent='Open Yoga / Mobility';b.onclick=()=>{const nav=[...document.querySelectorAll('.nav button,[data-v]')].find(x=>String(x.dataset?.v||'').toLowerCase()==='yoga'||x.textContent.trim().toLowerCase()==='yoga');if(nav)nav.click()};return b}
function render(){styles();const area=document.getElementById(AREA_ID),card=area?.querySelector('.workoutCard'),first=card?.querySelector('.exercise');if(!area||!card||!first)return;const name=workoutName(area);if(!name)return;area.querySelector('#'+PRE_ID)?.remove();area.querySelector('#'+POST_ID)?.remove();const w=warmup(name,area),pre=document.createElement('div');pre.id=PRE_ID;pre.className='dsPrepCard';pre.innerHTML=`<div class="dsPrepEyebrow">WARM-UP · REQUIRED</div><h3>Before your first working set</h3><div class="dsPrepText">${w.cardio}</div><ul class="dsPrepList">${w.moves.map(x=>`<li>${x}</li>`).join('')}</ul><div class="dsPrepDivider"></div><div class="dsPrepText"><b style="color:#fff">Ramp-up sets:</b> ${w.ramp}</div>`;first.before(pre);
const post=document.createElement('div');post.id=POST_ID;const c=cardioPlan(name);if(c.show){const box=document.createElement('div');box.className='dsPrepCard';box.innerHTML=`<div class="dsPrepEyebrow">CARDIO · PROGRAMMED</div><h3>${c.title}</h3><div class="dsPrepMeta">${c.time}</div><div class="dsPrepText">${c.text}</div>`;post.appendChild(box)}const cool=document.createElement('div');cool.className='dsPrepCard';cool.innerHTML=`<div class="dsPrepEyebrow">COOLDOWN · 3–6 MIN</div><h3>Post-workout stretch</h3><ul class="dsPrepList">${cooldown(name,area).map(x=>`<li>${x}</li>`).join('')}</ul><div class="dsPrepText" style="margin-top:8px">For a longer recovery session, use Yoga / Mobility.</div>`;cool.appendChild(yogaButton());post.appendChild(cool);const finish=[...card.querySelectorAll('button')].find(b=>/finish workout/i.test(b.textContent));if(finish)finish.before(post);else card.appendChild(post)}
function init(){styles();let lastSig='';const run=()=>{const area=document.getElementById(AREA_ID);if(!area)return;const sig=[workoutName(area),firstExerciseName(area),firstWorkingWeight(area),goal()].join('|');if(sig===lastSig&&document.getElementById(PRE_ID))return;lastSig=sig;render()};run();const area=document.getElementById(AREA_ID);if(area)new MutationObserver(muts=>{if(muts.every(m=>m.target.closest?.('#'+PRE_ID+',#'+POST_ID)))return;setTimeout(run,0)}).observe(area,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('#workoutTabs,.tab,.nav'))setTimeout(()=>{lastSig='';run()},0)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();