(()=>{
const PK='ds_profile_v2',YK='ds_yoga_sessions_v1',$=id=>document.getElementById(id),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const V={full:'https://www.youtube.com/watch?v=v7AYKMP6rOE',hips:'https://www.youtube.com/watch?v=Ho9em79_0qg',ham:'https://www.youtube.com/watch?v=u4gZgnCy5ew',back:'https://www.youtube.com/watch?v=4BOTvaRaDjI',shoulders:'https://www.youtube.com/watch?v=SedzswEwpPw',chest:'https://www.youtube.com/watch?v=SV7l1sfEmO0',balance:'https://www.youtube.com/watch?v=ATkEKbq72Hs',core:'https://www.youtube.com/watch?v=K-Ina_WW4Yc',rest:'https://www.youtube.com/watch?v=BiWDsfZ3zbo'};
const P=(n,t,s=45,v='full')=>({name:n,tags:t,sec:s,video:V[v]});
const POSES=[
P('Mountain Pose',['full','foundation'],45),P('Raised Hands Pose',['shoulders','chest'],30,'shoulders'),P('Standing Forward Fold',['hamstrings','back'],45,'ham'),P('Half Lift',['back','hamstrings'],30,'back'),P('Chair Pose',['legs','core'],45,'core'),P('Standing Side Bend',['core','lats'],30,'back'),
P('Downward-Facing Dog',['hamstrings','calves','shoulders','back'],60),P('Plank Pose',['core','shoulders'],45,'core'),P('Cobra Pose',['chest','back'],45,'back'),P('Upward-Facing Dog',['chest','shoulders','back'],40,'back'),P('Child’s Pose',['back','hips','shoulders','rest'],60,'rest'),P('Cat-Cow Flow',['back','core'],60,'back'),
P('Thread the Needle',['shoulders','upper back'],45,'shoulders'),P('Puppy Pose',['shoulders','lats','chest'],60,'shoulders'),P('Low Lunge',['hips','quads'],60,'hips'),P('High Lunge',['hips','legs','balance'],60,'hips'),P('Crescent Lunge',['hips','legs','shoulders'],60,'hips'),P('Lizard Pose',['hips','hamstrings'],60,'hips'),
P('Half Split',['hamstrings','calves'],60,'ham'),P('Pyramid Pose',['hamstrings','calves'],60,'ham'),P('Warrior I',['hips','legs','chest'],60),P('Warrior II',['hips','legs','shoulders'],60),P('Reverse Warrior',['hips','side body'],45),P('Extended Side Angle',['hips','side body','legs'],60),
P('Humble Warrior',['shoulders','chest','hips'],45,'shoulders'),P('Triangle Pose',['hamstrings','hips','side body'],60),P('Wide-Leg Forward Fold',['hamstrings','hips','back'],60,'ham'),P('Goddess Pose',['hips','legs'],60,'hips'),P('Garland Squat',['hips','ankles','legs'],60,'hips'),P('Tree Pose',['balance','hips','legs'],60,'balance'),
P('Eagle Pose',['balance','shoulders','hips'],60,'balance'),P('Warrior III',['balance','hamstrings','core'],60,'balance'),P('Half Moon Pose',['balance','hips','core'],60,'balance'),P('Dancer Pose',['balance','quads','chest'],60,'balance'),P('Seated Forward Fold',['hamstrings','back'],60,'ham'),P('Head-to-Knee Pose',['hamstrings','back'],60,'ham'),
P('Bound Angle Pose',['hips','adductors'],60,'hips'),P('Seated Wide-Leg Forward Fold',['hamstrings','hips'],60,'ham'),P('Hero Pose',['quads','ankles'],60,'hips'),P('Pigeon Pose',['glutes','hips'],75,'hips'),P('Reclined Pigeon',['glutes','hips'],60,'hips'),P('Frog Pose',['hips','adductors'],75,'hips'),
P('Happy Baby',['hips','lower back'],60,'hips'),P('Bridge Pose',['glutes','hamstrings','chest'],60,'back'),P('Sphinx Pose',['back','chest'],60,'back'),P('Locust Pose',['back','glutes'],45,'back'),P('Boat Pose',['core','hips'],45,'core'),P('Side Plank',['core','shoulders','balance'],45,'core'),
P('Bird Dog',['core','back','balance'],60,'core'),P('Supine Twist',['back','hips','rest'],60,'rest'),P('Reclined Bound Angle',['hips','rest'],90,'rest'),P('Legs Up the Wall',['hamstrings','calves','rest'],120,'rest'),P('Supported Child’s Pose',['back','hips','rest'],90,'rest'),P('Corpse Pose',['rest','full'],180,'rest'),
P('Neck Side Stretch',['neck','shoulders'],30,'shoulders'),P('Eagle Arms',['shoulders','upper back'],45,'shoulders'),P('Cow Face Arms',['shoulders','triceps'],60,'shoulders'),P('Reverse Prayer',['shoulders','chest'],45,'shoulders'),P('Hands-Clasped Chest Opener',['chest','shoulders'],45,'chest'),P('Standing Lat Reach',['lats','side body'],45,'back')
];
const FLOWS={'Recovery':['rest','back','hips'],'Full Body':['full','hips','hamstrings','shoulders','back','legs'],'Upper Body Release':['shoulders','chest','lats','upper back','triceps'],'Lower Body + Hips':['hips','glutes','hamstrings','quads','calves','legs'],'Core + Balance':['core','balance','hips'],'Restorative':['rest','back','hips']};
const prof=()=>{const p=read(PK,{});return {...p,yogaDays:Math.max(0,Math.min(7,+p.yogaDays||0))}},logs=()=>read(YK,[]);
function weekKey(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x.toISOString().slice(0,10)}
function weekLogs(){const w=weekKey();return logs().filter(s=>weekKey(new Date(s.date))===w)}
function hash(s){let x=0;for(const c of s)x=(x*31+c.charCodeAt(0))>>>0;return x}
function makeFlow(name,min){const tags=FLOWS[name]||FLOWS['Full Body'],pool=POSES.filter(p=>p.tags.some(t=>tags.includes(t))),out=[],used=new Set(),target=min*60;let total=0,i=hash(name+weekKey()+min)%pool.length;while(total<target&&used.size<pool.length){const p=pool[i%pool.length];i+=7;if(used.has(p.name))continue;used.add(p.name);out.push({...p});total+=p.sec}if(total<target){const r=POSES.find(p=>p.name==='Corpse Pose');out.push({...r,name:'Final Rest',sec:target-total})}return out}
const fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
let st={flow:'Recovery',min:20,poses:[],active:-1,left:0,timer:null};
function stop(){if(st.timer)clearInterval(st.timer);st.timer=null}
function startPose(i){stop();st.active=i;st.left=st.poses[i].sec;draw();st.timer=setInterval(()=>{st.left--;const t=$('dsYogaTimer');if(t)t.textContent=fmt(Math.max(0,st.left));const r=document.querySelector(`[data-yrow="${st.active}"] .dsYTime`);if(r)r.textContent=fmt(Math.max(0,st.left));if(st.left<=0){stop();st.active<st.poses.length-1?startPose(st.active+1):finish()}},1000)}
function finish(){stop();const a=logs();a.push({id:Date.now(),date:new Date().toISOString(),flow:st.flow,minutes:st.min,poses:st.poses.map(p=>p.name)});save(YK,a);st.active=-1;st.left=0;draw();alert('Yoga session saved.')}
function css(){if($('dsYogaStyles'))return;const s=document.createElement('style');s.id='dsYogaStyles';s.textContent='.dsYogaPanel{display:none}.dsYogaPanel.active{display:block}.dsYControls{display:grid;grid-template-columns:1.5fr .8fr;gap:8px;margin-top:10px}.dsYControls select,.dsYSettings select{background:#202020;border:1px solid #3b3b3b;color:#fff;border-radius:11px;padding:11px}.dsYRow{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid #292929}.dsYMeta{font-size:12px;color:#aaa;margin-top:3px}.dsYAct{display:flex;gap:8px;align-items:center}.dsYTime{min-width:40px;text-align:right;color:#ffbf47;font-weight:800}.dsYTimer{margin-top:12px;padding:14px;border:1px solid #4a2023;background:#251013;border-radius:14px}.dsYClock{font-size:34px;font-weight:950;margin-top:4px}.dsYSettings{margin-top:12px;padding-top:12px;border-top:1px solid #333}@media(max-width:430px){.dsYControls{grid-template-columns:1fr}}';document.head.appendChild(s)}
function ensure(){if(!$('yoga')){const w=$('workouts'),p=document.createElement('section');p.id='yoga';p.className='panel dsYogaPanel';p.innerHTML='<div id="dsYogaRoot"></div>';w.parentNode.insertBefore(p,w.nextSibling);const nav=document.querySelector('.navin');if(nav&&!nav.querySelector('[data-v="yoga"]')){nav.style.gridTemplateColumns='repeat(6,1fr)';const b=document.createElement('button');b.dataset.v='yoga';b.textContent='Yoga';nav.insertBefore(b,nav.querySelector('[data-v="progress"]'));b.onclick=()=>{document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));p.classList.add('active');b.classList.add('active');draw()}}}const set=document.querySelector('#settings .card');if(set&&!$('dsYogaSettings')){const box=document.createElement('div');box.id='dsYogaSettings';box.className='dsYSettings';const p=prof();box.innerHTML=`<b>Yoga plan</b><div class="muted small">Yoga is separate from lifting days.</div><label class="small">Yoga sessions/week<select id="dsYogaDays">${[0,1,2,3,4,5,6,7].map(n=>`<option value="${n}" ${n===p.yogaDays?'selected':''}>${n}</option>`).join('')}</select></label>`;set.appendChild(box);$('dsYogaDays').onchange=e=>{const p=read(PK,{});p.yogaDays=+e.target.value;save(PK,p);draw()}}}
function draw(){ensure();const r=$('dsYogaRoot');if(!r)return;const p=prof();if(!st.poses.length)st.poses=makeFlow(st.flow,st.min);const total=st.poses.reduce((n,x)=>n+x.sec,0),done=weekLogs().length;r.innerHTML=`<div class="card section"><div class="small red">YOGA / MOBILITY</div><h2 style="margin:5px 0 2px">Guided Yoga</h2><div class="muted small">${done}/${p.yogaDays} yoga sessions completed this week. Separate from your ${p.trainingDays||3} lifting days.</div><div class="dsYControls"><select id="dsYFlow">${Object.keys(FLOWS).map(n=>`<option ${n===st.flow?'selected':''}>${n}</option>`).join('')}</select><select id="dsYMin">${[10,15,20,30,45].map(n=>`<option value="${n}" ${n===st.min?'selected':''}>${n} min</option>`).join('')}</select></div><div class="row" style="margin-top:10px"><span class="pill">${st.poses.length} poses · ${Math.round(total/60)} min</span><button id="dsYStart" class="btn" type="button">${st.active>=0?'Restart':'Start Flow'}</button></div>${st.active>=0?`<div class="dsYTimer"><div class="small red">NOW</div><b>${st.poses[st.active].name}</b><div id="dsYogaTimer" class="dsYClock">${fmt(st.left)}</div><div class="row"><button id="dsYPrev" class="btn secondary">Previous</button><button id="dsYNext" class="btn secondary">Next</button><button id="dsYFinish" class="btn good">Finish</button></div></div>`:''}</div><div class="card section"><h3 style="margin-top:0">Today’s flow</h3>${st.poses.map((x,i)=>`<div class="dsYRow" data-yrow="${i}"><div><b>${i+1}. ${x.name}</b><div class="dsYMeta">${x.tags.slice(0,3).join(' · ')}</div></div><div class="dsYAct"><span class="dsYTime">${i===st.active?fmt(st.left):fmt(x.sec)}</span><a class="demo" href="${x.video}" target="_blank" rel="noopener">▶ Demo</a></div></div>`).join('')}</div><div class="card section"><h3 style="margin-top:0">Yoga library</h3><div class="muted small">${POSES.length} timed poses across full body, recovery, hips, legs, back, shoulders, chest, core, balance and restorative work.</div></div>`;$('dsYFlow').onchange=e=>{stop();st.flow=e.target.value;st.poses=makeFlow(st.flow,st.min);st.active=-1;draw()};$('dsYMin').onchange=e=>{stop();st.min=+e.target.value;st.poses=makeFlow(st.flow,st.min);st.active=-1;draw()};$('dsYStart').onclick=()=>startPose(0);if($('dsYPrev'))$('dsYPrev').onclick=()=>startPose(Math.max(0,st.active-1));if($('dsYNext'))$('dsYNext').onclick=()=>st.active<st.poses.length-1?startPose(st.active+1):finish();if($('dsYFinish'))$('dsYFinish').onclick=finish}
function init(){css();ensure();draw();const q=document.querySelector('.quick');if(q&&!q.querySelector('[data-go-yoga]')){const b=document.createElement('button');b.className='action';b.type='button';b.dataset.goYoga='1';b.innerHTML='<b>🧘</b>Yoga';q.appendChild(b);b.onclick=()=>document.querySelector('.nav [data-v="yoga"]')?.click()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();